spring.application.name=Paliwex
spring.datasource.url=jdbc:postgresql://localhost:5432/paliwex_db
spring.datasource.username=postgres
spring.datasource.password=haslo123

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always